backend:
  name: git-gateway

media_folder: static/images/uploads
public_folder: /uploads

collections:
  - name: 'posts'
    label: 'Public Posts'
    folder: 'content'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publication Date", name: "datePublished", widget: "datetime" }
      - { label: "Modification Date", name: "dateModified", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Cover Image Alt", name: "coverAlt", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }